### ISSUE TITLE
Unable to display 37.10 

### ISSUE THREAD

**Issue by arronorionfive** [Seeed-Studio/Grove_4Digital_Display#10]
While using the example DisplayNum
```
float num=37.10;
tm1637.displayNum(num, 2);
```

output on 7 seg will show 37.09

Does anyone else have this issue??

**Comment by Combinacijus** [comment]
Does this only happen with 37.10? Guessing it might be a float problem maybe due to way they are represented in computer memory 37.10 could be represented as 37.099999999... 
Could you check if printing num with all decimal places would actually print 37.10 and not the other one?
Even though that might be the case displayNum function still should account for that.

**Comment by Pillar1989** [comment]
Has the problem been solved?  @Combinacijus

**Comment by Combinacijus** [comment]
Just made a merge request. It should solve it @Pillar1989
