### ISSUE TITLE
Arduino without PC

### ISSUE THREAD

**Issue by BodnaBersch** [Seeed-Studio/Grove_4Digital_Display#19]
I coded a program but it is only working with the PC connected. If the PC isn`t connected the Timer doesn´t work properly it only counts up to 2 or 3. I Have no Idea.

[ADUINO UNO R3]
[main.zip](https://github.com/Seeed-Studio/Grove_4Digital_Display/files/8079568/main.zip)
![image](https://user-images.githubusercontent.com/99805763/154259172-b78fbe31-2963-478e-8de8-0ba5673265fd.png)
![image](https://user-images.githubusercontent.com/99805763/154259256-88f1e817-8f7a-478c-b978-15f03fb4fb9f.png)

**Comment by Combinacijus** [comment]
I have a few notes not sure if thiese would fix your problem tho
1. Sensor() uses pulseIn() function which is blocking this might block execution or atleast make it slower if no pulse is detected. So maybe try commenting line 37
2. Timer() counts seconds by sleeping for 1000ms which is not accurate because you don't take into account time it takes to run code (especially unknown pulseIn blocking time). For this I would adapt ideas from non blocking sleep sketch. Basically to use millis() or micros() to check if 1sec have passed.
3. Line 100 and 102 don't mix bool with int. Technically it works but readability is worse
4. If nothing works I would keep only Timer() inside loop() without any if statement to rule out any mistakes in those

**Comment by lakshanthad** [comment]
Hello @BodnaBersch,

Have you followed the tips from @Combinacijus? Any updates on the issue now?

Thank you.

**Comment by ackPeng** [comment]
@BodnaBersch Hi, does this problem still exist?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
